type Ingredient @embedded {
  key: String!
  item: String!
  amount: Float!
  unit: String!
}

type Step @embedded {
  key: String!
  text: String!
}

type User {
  authId: String!
  nickname: String!
  favorites: [String!]
  recipes: [Recipe] @relation(name: "recipe_author")
  avatar: String
}

type Recipe {
  title: String!
  image: String
  description: String
  date: String!
  ingredients: [Ingredient!]! 
  method: [Step!]!
  user: User! @relation(name: "recipe_author")
}

type Query {
  allRecipes: [Recipe]
  allUsers: [User]
  getUserByAuthId(authId: String!): User
}