type Ingredient @embedded {
  key: String!
  item: String!
  amount: Float!
  unit: String!
}

type Step @embedded {
  key: String!
  text: String!
}

type User {
  favorites: [Recipe] @relation
}

type Recipe {
  title: String!
  image: String
  description: String
  date: String!
  ingredients: [Ingredient!]! 
  method: [Step!]!
  user: User!
}

type Query {
  allRecipes: [Recipe]
}